### ISSUE TITLE
Packages to support

### ISSUE THREAD

**Issue by malcolmbarrett** [r-lib/ymlthis#11]
- [x] blogdown 
- [x] bookdown 
- [x] pkgdown 
- [x] rticles
- [x] pagedown
- [x] learnr (no top-level yaml to support)
- [x] xaringan (no top-level yaml to support)
- [x] revealjs (no top-level yaml to support)
- [x] distill
- [x] flexdashboard (no top-level yaml to support)
- [x] rsconnect/email  + `rmd_output_metadata()`
- [x] include an example using a third party package

**Comment by apreshill** [comment]
xaringan?

**Comment by malcolmbarrett** [comment]
Yes, thank you! I don't recall top level YAML off the top of my head but I'll cross check ❎

**Comment by malcolmbarrett** [comment]
I should check revealjs, too

**Comment by apreshill** [comment]
Also distill potentially, but that probably overlaps a lot with your current site yml functions

Flexdashboard too

**Comment by malcolmbarrett** [comment]
Yeah, I did look at those and basically found the same but I'm going to add them just in case
