### ISSUE TITLE
convert toml to yaml?

### ISSUE THREAD

**Issue by njtierney** [r-lib/ymlthis#28]
I recently converted some TOML file to YAML, and I was wondering if this might be something in scope for ymlthis? In the spirit of: "YAML this TOML"? A function like `toml_to_yaml(path = "path/to/file.toml")`?

**Comment by malcolmbarrett** [comment]
I did think about that, as I have an internal function  that does that using `blogdown::hugo_cmd(args = c("convert", "toYAML", "--unsafe"))`. Definitely willing to export that internal code.

Are you imagining such a function would read it in as YAML (a `yml` object, in this case) or convert the file to `path/to/file.yml`?

**Comment by malcolmbarrett** [comment]
Actually, Hugo supports back and forth conversion to YAML, TOML, and JSON, so I think what I'd like to do is something like `read_toml()`/`read_json()` that converts to a `yml` object and `use_toml()`/`use_json()` to write it out in those formats

**Comment by njtierney** [comment]
Glad to hear there is some existing code :tada:

For my use case I'd probably just prefer to specify where I write it to, and then I can delete the TOML file (to avoid a case where you overwrite the TOML as YAML and then can't go back in case you, say, didn't use version control).

But I could also see the use for reading it in as `yml` object!

Just saw your second comment.

`read_toml()` sounds good, but I'm not sure if `use_toml()` evokes the transpiling - to me I think of `usethis` and would expect it to write a fresh TOML or something. How about `to_yaml()` or `as_toml()`?

**Comment by malcolmbarrett** [comment]
hmm I picked that to match the other file writing functions, but maybe you're right. I'll think about it

**Comment by malcolmbarrett** [comment]
added `read_toml()`, `read_json`, `write_as_toml()`, and `write_as_json()`. Thanks for the suggestions and let me know if you have any issues with it!

**Comment by njtierney** [comment]
Nice! I'll test it out. :)

**Comment by njtierney** [comment]
Looks good to me!

``` r

library(ymlthis)

the_toml <- read_toml("https://raw.githubusercontent.com/yihui/hugo-ivy/master/theme.toml")
#> Warning in find_exec("hugo", "Hugo", "You can install it via
#> blogdown::install_hugo()"): Found hugo at "~/Library/Application Support/
#> Hugo/hugo" and "/usr/local/bin/hugo". The former will be used. If you don't
#> need both copies, you may delete/uninstall one.

the_toml
#> ---
#> author:
#>   homepage: https://yihui.name
#>   name: Yihui Xie
#> description: A theme ported from Ivy
#> features: blog
#> homepage: https://ivy.yihui.name
#> license: Unlicense
#> licenselink: https://github.com/yihui/hugo-ivy/blob/master/LICENSE.md
#> min_version: '0.18'
#> name: Ivy
#> original:
#>   author: dmulholland
#>   homepage: http://mulholland.xyz/docs/ivy/
#>   repo: https://github.com/dmulholland/ivy
#> tags:
#> - minimal
#> - blog
#> - personal
#> - clean
#> - simple
#> - minimalist
#> ---
ymlthis::is_yml(the_toml)
#> [1] TRUE
```

<sup>Created on 2019-07-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
