### ISSUE TITLE
Add `ymlthis::` prefix to options for .Rprofile?

### ISSUE THREAD

**Issue by batpigandme** [r-lib/ymlthis#31]
Hey,

Great package! I just added a few ymlthis options à la:
https://github.com/r-lib/ymlthis/blob/0642b68edc35ea4f2259b7ddf9c32dddb8de6dec/vignettes/introduction-to-ymlthis.Rmd#L243-L255

For the example options shown, you need to either prefix them (the option I went with) or attach ymlthis. The below works in `.Rprofile` on a fresh R session.
```r
   ymlthis.rmd_body = c( 
     "", 
     ymlthis::setup_chunk(), 
     "", 
     ymlthis::code_chunk( 
       library(ymlthis) 
     ) 
```

Happy to do a PR to make the change, but wanted to check in first.

**Comment by malcolmbarrett** [comment]
Oh yeah, that makes total sense; I'm really talking about `.Rprofile` here so it should be set up to work there. I may be changing that part to text output (to match the result of passing that vector to `use_rmd_defaults()`), but I'll make your change for now. Thanks!
