### ISSUE TITLE
pandoc not found unlike with rmarkdown - use Rstudio Pandoc ? 

### ISSUE THREAD

**Issue by cderv** [r-lib/ymlthis#32]
I got this error

``` r
ymlthis::use_pandoc_highlight_style("pygments", "test.theme")
#> Error in system2("pandoc", args = args, stdout = TRUE): '"pandoc"' not found
```

<sup>Created on 2019-08-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

There is indeed a check in the function
```r
stop_if_pandoc_not_installed()
```
that uses `rmarkdown::pandoc_available()` which uses `Sys.getenv("RSTUDIO_PANDOC")` in addition of pandoc in PATH. 

So this is `TRUE` on my setup because I am in RStudio so pandoc is found
``` r
rmarkdown::pandoc_available()
#> [1] TRUE
(rmarkdown:::find_pandoc())
#> $version
#> [1] '2.7.2'
#> 
#> $dir
#> [1] "C:/Program Files/RStudio/bin/pandoc"
```

I think this package should use the same mechanism and maybe use directly `rmarkdown::pandoc_exec()`. The fact that the PATH should not be modified when using Rmarkdown is a good thing.

``` r
system2(rmarkdown::pandoc_exec(), "--print-highlight-style=pygments")
```

I can help with a PR if needed.

**Comment by malcolmbarrett** [comment]
Thanks for the suggestion! I agree that that's much better.

**Comment by malcolmbarrett** [comment]
(and please let me know if that doesn't fix the issue)

**Comment by cderv** [comment]
Thanks for the fix, it works.

About 

> pandoc_citeproc_exec <- function() {
  paste0(rmarkdown::pandoc_exec(), "-citeproc")
}

In case you don't know there is a `rmarkdown:::pandoc_citeproc()` that could be useful here. It is not exported but I believe it could. It deals with some _pandoc-citeproc_ exe not installed with pandoc but available in PATH. 

Idea : Having `ymlthis ` based on all rmarkdown ways of dealing with pandoc can be a good idea to avoid already dealt issues... There is a lot of utils function for pandoc there :thinking: A pandocdown utilitily package could be event be useful 😄

**Comment by malcolmbarrett** [comment]
Thanks for the tip! I did not know about that one. It's my intention use solutions to problems solved by the *down packages in ymlthis. The larger problem is that they have solved so many, I don't know about them all! If you see any others where I am duplicating efforts, let me know. I changed `pandoc_citeproc_exec()` to more closely reflect `rmarkdown:::pandoc_citeproc()` since it's pretty simple.

I agree, though, that it would be good to have a pandoc package!

**Comment by cderv** [comment]
I know quite well some of the internals of some *down packages as I am use to help with them, mainly knitr and rmarkdown. So  I can definitely help with that. 
I think it is also possible to export some currently unexported function in rmarkdown so that you don't duplicate. 
And by the way, very nice idea this package!
