### ISSUE TITLE
Why the name filed instead of author ? 

### ISSUE THREAD

**Issue by cderv** [r-lib/ymlthis#33]
I may have missed something but why by default author is set to a name field  ? 
Default field for Rmarkdown are often `date`, `title`, `author`, `output`, but no `name` field

``` r
library(ymlthis)
# add a name field but not author
yml()
#> ---
#> name: Christophe Dervieux
#> date: '`r format(Sys.Date())`'
#> ---
yml(author = TRUE)
#> ---
#> name: Christophe Dervieux
#> date: '`r format(Sys.Date())`'
#> ---

# do not add the author name field
"author: Christophe Dervieux\n" %>% 
  yml(author = TRUE)
#> ---
#> author: Christophe Dervieux
#> date: '`r format(Sys.Date())`'
#> ---

# add another author field
yml() %>%
  yml_author("Christophe Dervieux")
#> ---
#> name: Christophe Dervieux
#> date: '`r format(Sys.Date())`'
#> author: Christophe Dervieux
#> ---
```

<sup>Created on 2019-08-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

In the [doc](https://r-lib.github.io/ymlthis/articles/yaml-overview.html), it is not clear as the example is 
```yaml
---
name: Malcolm Barrett
---
```
> In R, the equivalent structure is a list with named character vector: **list(author = "Malcolm Barrett")**. In fact, you can call this list in R Markdown using the metadata object: **metadata$author** will return the YAML in the metadata header.

Again, I may have misunderstood something here but I find it odd to have two field with a name. 
I have to add explicitly the author but the doc says 
> By default, **yml() looks for your name** (using getOption("usethis.full_name"), getOption("devtools.name"), and whoami::fullname()) and uses today's date **to use in the author** and date fields respectively

Let's note that with default pandoc template, author field can be one element string or can have name, affiliation and email elements. 

Is there something to change here ? 
Thanks.

**Comment by malcolmbarrett** [comment]
🤦‍♂🤦‍♂🤦‍♂🤦‍♂🤦‍♂🤦‍♂🤦‍♂🤦‍♂🤦‍♂🤦‍♂🤦‍♂🤦‍♂🤦‍♂🤦‍♂🤦‍♂🤦‍♂🤦‍♂🤦‍♂🤦‍♂

Just a bug that's so obvious I never noticed

**Comment by cderv** [comment]
Glad I could help ! 😄

**Comment by malcolmbarrett** [comment]
It's much appreciated!
