### ISSUE TITLE
Errors with yml_params() with shiny input.

### ISSUE THREAD

**Issue by apreshill** [r-lib/ymlthis#36]
Hey @malcolmbarrett,

I'm experiencing issues whenever I try to use `yml_params()` with shiny input. Here is a reprex using this from the [vignette](https://ymlthis.r-lib.org/articles/introduction-to-ymlthis.html#parameterized-reports):

``` r
library(tidyverse)
library(ymlthis)

yml() %>%
  yml_params(
    data = shiny_file("Upload Data (.csv)"),
    n = shiny_numeric("n to sample", 10),
    date = shiny_date("Date"),
    show_plot = shiny_checkbox("Plot the data?", TRUE)
  )
#> Internal error: Expected call in `quo_invert()`
```

<sup>Created on 2019-09-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

R Markdown spits out this error:

<img width="889" alt="Screen Shot 2019-09-29 at 6 05 26 PM" src="https://user-images.githubusercontent.com/12160301/65828944-c873da00-e2e3-11e9-9deb-3ee3614a6233.png">

**Comment by malcolmbarrett** [comment]
Thanks! I can't replicate this, but I'm wondering if I have an unrealized version dependency between imported packages. Could you try re-installing rlang, shiny, and purrr? It would be helpful for me if you could do it one at a time. Then we'd know which (if any) solved it

**Comment by apreshill** [comment]
woohoo that fixed it! Thank you :) It was odd because I had existing code in some xaringan slides that worked but last night wouldn't knit for me. I wonder what happened with those other packages? Anyway, solved!

**Comment by malcolmbarrett** [comment]
Good! Any sense of which package update fixed it?

**Comment by apreshill** [comment]
I would bet `rlang`, and I never explicitly use it so probably only updates upon installation of packages that use it. I had just updated shiny for another reason, so not that one.
