### ISSUE TITLE
quiet not passed in ymlthis:::write_yml_file

### ISSUE THREAD

**Issue by dchiu911** [r-lib/ymlthis#37]
In `ymlthis:::write_yml_file()`, the `quiet` param is never passed to `usethis::write_over()`

https://github.com/r-lib/ymlthis/blob/master/R/use_yml.R#L181
https://github.com/r-lib/ymlthis/blob/master/R/use_yml.R#L191

**Comment by malcolmbarrett** [comment]
Good catch. Thanks!!
