### ISSUE TITLE
Extra line return when using yaml::as.yaml

### ISSUE THREAD

**Issue by dchiu911** [r-lib/ymlthis#38]
Using `yaml::as.yaml()` to convert to a YAML string appends an extra line return at the end. This creates 2 newlines at the end of `_bookdown.yml` since I already have the setting `AutoAppendNewline: Yes` in my R project.
``` r
library(ymlthis)
bookdown_yml <- yml_empty() %>%
  ymlthis::yml_bookdown_opts(
    book_filename = "book",
    before_chapter_script = "src/utils.R",
    rmd_subdir = "src"
  )
yaml::as.yaml(bookdown_yml)
#> [1] "book_filename: book\nbefore_chapter_script: src/utils.R\nrmd_subdir: src\n"
use_bookdown_yml(bookdown_yml, path = ".", quiet = TRUE)
#> ✔ Writing '/private/var/folders/xs/bp9xghmn1sdfp3h6yz2j389nq5fs7n/T/RtmpPg6xuP/reprex145a2cf42a87/_bookdown.yml'
readLines("./_bookdown.yml")
#> [1] "book_filename: book"               
#> [2] "before_chapter_script: src/utils.R"
#> [3] "rmd_subdir: src"                   
#> [4] ""
```

<sup>Created on 2019-10-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by malcolmbarrett** [comment]
Hm, I'm not sure the best approach to handling this. As you say, this is the result of the yaml package and your local settings. @rich-iannone, what do you think? maybe an option in the write functions to check, e.g. `options(ymlthis.remove_blank_line = TRUE)` & will then remove the last `\n`?

**Comment by rich-iannone** [comment]
Hey Malcolm, I like the idea of a dedicated option for this. Defaulting to `TRUE` is a good choice.

**Comment by malcolmbarrett** [comment]
Hmm it seems that the default for when you create a project in RStudio is `AutoAppendNewline` is omitted but usethis/devtools set `AutoAppendNewline: Yes` (at least on my computer). It might be safer not to delete the last line by default
