### ISSUE TITLE
Improve use_index_rmd

### ISSUE THREAD

**Issue by dchiu911** [r-lib/ymlthis#39]
There are two features I would like to request:

1. Pass the `body` param from `use_rmarkdown()` to `use_index_rmd()`. I'm trying to write `\n# Preface {-}` write after the `index.Rmd` YAML.
2. `use_index_rmd()` forces `index.Rmd` to open under the current conditions `rstudioapi::isAvailable() && interactive()`. It would be nice to be able to turn this off so one can write silently like for `_bookdown.yml` and `_output.yml`.

**Comment by malcolmbarrett** [comment]
1) Makes total sense
2) This too. Is something like `open_doc = interactive()` as an argument good with your workflow? It will open by default but you can turn it off. It will still check for RStudio on the inside.

**Comment by dchiu911** [comment]
2. Yes that would work well!

**Comment by malcolmbarrett** [comment]
Great, thanks!
