### ISSUE TITLE
Question about bib params

### ISSUE THREAD

**Issue by dchiu911** [r-lib/ymlthis#40]
I see that both `yml_citations()` and `yml_latex_opts()` have the `bibliography` param. Intuitively, I expected both `biblio_style` and `biblio_title` params to be available in `yml_citations()`, but it's only in `yml_latex_opts()`. Would it make sense to make them available in `yml_citations()` or would that present some potential problems?

``` r
library(ymlthis)

yml_empty() %>% 
  yml_latex_opts(bibliography = "book.bib")
#> ---
#> bibliography: book.bib
#> ---

yml_empty() %>% 
  yml_citations(bibliography = "book.bib")
#> ---
#> bibliography: book.bib
#> ---

yml_empty() %>% 
  yml_latex_opts(biblio_style = "apalike",
                 biblio_title = "References")
#> ---
#> biblio-style: apalike
#> biblio-title: References
#> ---

# Add this?
# yml_empty() %>% 
#   yml_citations(biblio_style = "apalike",
#                 biblio_title = "References")
```

<sup>Created on 2019-10-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by malcolmbarrett** [comment]
It makes sense to me. Thanks for this and the other issues!
