### ISSUE TITLE
Addin failing to launch - Error in : `.y` is not a vector (pairlist)

### ISSUE THREAD

**Issue by csrvermaak** [r-lib/ymlthis#48]
Get the following when launching addin:

```
> ymlthis:::launch_yaml_addin()

Listening on http://127.0.0.1:5966
Warning: Error in : `.y` is not a vector (pairlist)
  79: purrr::map2
  78: ui_function_args [C:\Users\rvermaak\Documents\R\win-library\3.5\ymlthis\addin\new_yaml/global.R#30]
  68: .f [C:\Users\rvermaak\Documents\R\win-library\3.5\ymlthis\addin\new_yaml/global.R#53]
  67: purrr::map
  66: ui_output_modals [C:\Users\rvermaak\Documents\R\win-library\3.5\ymlthis\addin\new_yaml/global.R#68]

```

**Comment by malcolmbarrett** [comment]
Could you please update purrr and rlang and see if that resolves the issue?

**Comment by malcolmbarrett** [comment]
HI @csrvermaak, could you please let me know if updating those two packages works for you? If it does not, will you please supply your session info via `xfun::session_info()`?

**Comment by csrvermaak** [comment]
Hi @malcolmbarrett, apologies for not getting back to you sooner. Unfortunately I can't currently update the packages, as it is a production environment, and I'd need to run all units tests etc if I update. I will get to this in due course, and let you know. But from my initial investigation I am almost 100% certain that you are right, and it is simply my package versions that need updating.

**Comment by malcolmbarrett** [comment]
Ah ok, no worries. Let me know if that doesn't resolve it.

**Comment by malcolmbarrett** [comment]
Hi, I'm going to close this issue, since it's a bit stale. Feel free to reopen if it turns out not to be resolved.
