### ISSUE TITLE
404 error for pkgdown site

### ISSUE THREAD

**Issue by apreshill** [r-lib/ymlthis#56]
https://ymlthis.r-lib.org/

**Comment by malcolmbarrett** [comment]
Thanks for the heads up! Hm, it seems like the GitHub pages site is working right (https://r-lib.github.io/ymlthis/). Might be something with the `r-lib.org` redirect? I think @hadley set that up

**Comment by hadley** [comment]
The problem is that your pkgdown work isn't calling `pkgdown::deploy_to_branch()`, which is now in charge of making the `CNAME` file that GitHub needs to make the subdomain work.

**Comment by malcolmbarrett** [comment]
Ah, ok. Thanks! Well, maybe this is a good excuse to change this to GH Actions anyway.

**Comment by malcolmbarrett** [comment]
That did the trick. Thanks to you both!
