### ISSUE TITLE
ymlthis for csvy?

### ISSUE THREAD

**Issue by tvc-amaffei** [r-lib/ymlthis#57]
Hi. I was wondering if any prior work has been done looking at developing ymlthis functions for yaml frontmatter for csv files (aka csvy) ? Thank you.
https://github.com/leeper/csvy#import-and-export-csv-data-with-a-yaml-metadata-header

**Comment by malcolmbarrett** [comment]
I'm afraid not. Unfortunately, it's a slippery slope to try to keep up with all variants of yaml in the R world, so this project focuses on R Markdown-related tools

**Comment by tvc-amaffei** [comment]
I love the approach taken in ymlthis and am considering to duplicate this pattern for use with csvy files. If you have any thoughts on another R yaml package, community, or interested party that I might contact I'd appreciate the pointer. Otherwise I'll think about creating a new package along these lines. Thank you!

**Comment by malcolmbarrett** [comment]
Nothing comes to mind, but if you like the pattern here, it's certainly possible to extend it into a new package. ymlthis *supports* other YAML, it just doesn't offer helper functions for them. So, if you like the way the package works, `as_yml()` and friends are easy to use in other cases. Check out the source code for some of the `yml_()` functions and you'll see the pattern is usually quite simple: make a list, then spit it out into a `yml` object
