### ISSUE TITLE
New theme YAML key in distill

### ISSUE THREAD

**Issue by apreshill** [r-lib/ymlthis#59]
For a single article in its own yaml, or in `_site.yml`:
```
---
output: 
  distill::distill_article:
    theme: theme.css
---
```

**Comment by malcolmbarrett** [comment]
Thanks! Any additional arguments via the output function are naturally handled by `yml_output()` as-is 😌 

``` r
library(ymlthis)
yml_output(
  yml_empty(), 
  distill::distill_article(theme = "theme.css")
)
#> ---
#> output:
#>   distill::distill_article:
#>     theme: theme.css
#> ---
```

<sup>Created on 2020-10-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
