### ISSUE TITLE
R fatal error when using "é" in yml_params

### ISSUE THREAD

**Issue by But2ene** [r-lib/ymlthis#67]
``` r
ymlthis::yml_empty() %>%
  ymlthis::yml_params(
    filepath = "with_é"
  )
# > Fatal Error
```
<sup>Created on 2021-06-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I ran the code on windows. The encoding of my OS is "windows-1252", whereas the encoding of my files is always UTF-8.

I would like to use strings that contain accentuated character in `yml_params`. However, it creates a fatal error. It makes me restart the Rstudio session. I would like to continue using `ymlthis` because it helps me a lot in Rmarkdown automation. Does an alternative / solution exists?

**Comment by malcolmbarrett** [comment]
Do you have this error when you run `yaml::as.yaml(list(params = list(file_path = "with_é")))`? I'm not sure if this is an issue with rendering it or printing it, but I know yaml has had some issues similar to this

**Comment by malcolmbarrett** [comment]
Closing this since I haven't heard and I think it's a `yaml` issue
