### ISSUE TITLE
use_rmarkdown(): force overwrite existing file (non-interactive mode)

### ISSUE THREAD

**Issue by sbock17** [r-lib/ymlthis#74]
Hello all, 

How could it be be possible to let ```ymlthis``` overwrite an existing file and therefore updating it, using the ```use_rmarkdown()``` function?

I tested it but the prompt (asking for different numbers just for overwriting my temporary file) is a big drawback:
```
Overwrite pre-existing file 'new_written_file.rmd'?

1: I agree
2: Negative
3: Absolutely not

Auswahl: 1
✔ Writing 'new_written_file.rmd'
>
```

I've read, that this means I'm running R in the  interactive mode, and I should go for a script to be non-interactive (batch) mode. 
So I have completed a working shell script running R, but still, the overwriting of files is not possible - no prompt, this time justt stating 
```
> ✔ Leaving 'new_written_file.rmd' unchanged
```

I have basic settings like this for the bash script executing R:
```sh
Rscript -e "
```
```r
require(rmarkdown);
require(magrittr);
require(ymlthis);


# 
temp1= 'new_written_file.rmd';
mytemplate= 'the_template_which_has_some_yaml_to_extract.rmd';
themarkdownfile='myactualfile.rmd;

x <- yml() %>% ## I do this only to make sure the yaml is not interfered
yml_discard(c('author', 'date' ));

# Here starts the problem:
use_rmarkdown(
  .yml = x,
  path = temp1,
  template = mytemplate,
  include_yaml = TRUE,
  include_body = FALSE,
  body = NULL,
  overwrite = TRUE,
  quiet = FALSE);

# Usually works if the file is new, but now the following:

use_rmarkdown(
  path = temp1,
  template = themarkdownfile
  include_yaml = TRUE,
  include_body = TRUE,
  body = NULL,
  quiet = FALSE);

#> ✔ Leaving 'new_written_file.rmd' unchanged
"
# … The file is not written :'(
```
I've tried something like  ``` overwrite = TRUE, ```...  ```open_doc= FALSE``` or ```interactive(FALSE)```, or ```non-interactive()``` …… But I have no solution.. 

If I am doing it interactively, I have to type in a different number all the time for the prompt for the overwriting of the file, here called ```temp1```. So it works very nice in interactive mode, but I want to have it generated automatically, as part of a complex script.

I really hope the answer would simply be setting a hidden option in:
```r
use_rmarkdown(
  open_doc = interactive()
)
```
? 

But I have not yet found an answer. I wish, someone with some experience using R, could give me a hint or even solution?

Kind regards :)

**Comment by mattwarkentin** [comment]
@malcolmbarrett I am running into this issue also. It seems like the writing of the file is handled by `usethis::write_over()` which does not do any overwriting without explicit opt-in by the user - which means it does not work programatically in a script/package.

> write_over: writes a file with specific lines, creating it if necessary or overwriting existing, if proposed contents are not identical and **user is available to give permission**.

It would be nice if `ymlthis::use_rmarkdown` and friends had a `force` argument to force the overwrite in non-interactive mode. What do you think?

**Comment by mattwarkentin** [comment]
Frustratingly, even something like this fails:
```r
withr::with_options(
  list(usethis.overwrite = TRUE),
  ymlthis::use_rmarkdown(...)
)
```

Because in order to overwrite non-interactively you not only need to set `usethis.overwrite` to `TRUE` but the file needs to be inside an RStudio Project and a git repository. Seems unnecessarily strict to me.

I think this is limiting the ability to program with `{ymlthis}`.

**Comment by malcolmbarrett** [comment]
Yes, I agree. Happy to accept a PR for an `overwrite` argument. Otherwise, I'll work on this soon

**Comment by sbock17** [comment]
@mattwarkentin I am very glad someone else ran into the same issue, indeed it is limiting the ability to „program with `{ymlthis}`“. I even completely halted a private project dependent on {`ymlthis`} to wait for a solution :D 

Very nice to hear you would take some time investigating the possibilities of including an `overwrite` argument, @malcolmbarrett, I would be very happy for a solution!

Kind regards :)

**Comment by andvon** [comment]
Could this be done for `ymlthis::use_yml_file` as well?

Otherwise, this package is exceptional; thanks for your efforts.
