### ISSUE TITLE
status of the project

### ISSUE THREAD

**Issue by Polkas** [r-lib/ymlthis#76]
I will be glad to get the response if the project will be continued. 
It is a great tool nevertheless on the current state (very low covr and lack of activity) it could not be a dependency for a production level apps.
Sb could assume the project is abandoned if check the development stage of https://github.com/r-lib/ymlthis/milestone/2.
Thanks

**Comment by malcolmbarrett** [comment]
It is not abandoned, although it's not receiving a lot of attention from me right now
