### ISSUE TITLE
Typo in addins.R

### ISSUE THREAD

**Issue by tonycmac** [r-lib/ymlthis#84]
Apologies for likely not submitting this correctly - first time writing an issue.

I'm getting an error launching ymlthis:::launch_yaml_addin(). I believe this is due to a typo in your addins.R file (https://github.com/r-lib/ymlthis/blob/37f50c303b97efb26e8ed7fc2ba73f4d0ae94a95/R/addins.R) where you have miniIU instead of miniUI package being listed.

Below is my console output (newest version of RStudio - 2022.07.1 Build 554) on R 4.1.3

`ymlthis:::launch_yaml_addin()
i The package `miniIU` is required Must be installed to use this function.
x Would you like to install it?

1: Yes
2: No

Selection: 1
v Loading metadata database ... done
<callr_error/rlib_error_3_0/rlib_error/error>                              
Error: 
! error in callr subprocess
Caused by error: 
! Cannot install packages:
* miniIU: Can't find package called miniIU.
---
Subprocess backtrace:
 1. base::withCallingHandlers(cli_message = function(msg) { ...
 2. get("pkg_install_make_plan", asNamespace("pak"))(...)
 3. prop$stop_for_solution_error()
 4. private$plan$stop_for_solve_error()
 5. pkgdepends:::pkgplan_stop_for_solve_error(self, private)
 6. base::stop("Cannot install packages:\n", msg, call. = FALSE)
 7. | base::.handleSimpleError(function (e) ...
 8. global h(simpleError(msg, call))
 9. base::stop(e)
10. global (function (e) ...
<simpleError: Cannot install packages:
* miniIU: Can't find package called miniIU.>
NULL
Error: ! error in callr subprocess
Caused by error: 
! Cannot install packages:
* miniIU: Can't find package called miniIU.
Type .Last.error.trace to see where the error occurred`

**Comment by tonycmac** [comment]
Cloned the repo locally, changed "miniIU" to "miniUI" on line 3 of addins.R and then ran devtools::load_all() and the add-in worked perfectly again!

![image](https://user-images.githubusercontent.com/61159841/181408148-420e6bc6-3230-418e-bb6a-971078d44fa2.png)

**Comment by malcolmbarrett** [comment]
Thanks!
