### ISSUE TITLE
Why don't all YAML document options work?

### ISSUE THREAD

**Issue by kputschko** [r-lib/ymlthis#90]
I'm working in an empty Quarto file attempting to modify options outside the normal few, and I can change the title and subtitle easily, but not the title block banner color. Why not?

```
ymlthis::yml_empty() |> 
  ymlthis::yml_toplevel(
    title = "Testing Title",
    subtitle = "Testing Subtitle",
    "title-block-banner" = "#527798")
```

**Comment by malcolmbarrett** [comment]
I don't understand your question. Can you clarify? I see all three in the output

``` r
ymlthis::yml_empty() |> 
  ymlthis::yml_toplevel(
    title = "Testing Title",
    subtitle = "Testing Subtitle",
    "title-block-banner" = "#527798")
#> ---
#> title: Testing Title
#> subtitle: Testing Subtitle
#> title-block-banner: '#527798'
#> ---
```

<sup>Created on 2024-09-09 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Note that ymlthis was created before Quarto. I don't think it needs to support Quarto because Quarto activates much better yaml linting and autocomplete in IDEs than R Markdown

**Comment by kputschko** [comment]
Ah, thanks for the clarifying question. Yes it produces the expected output in the console, but the options don't translate to the header YAML options, and when knitting the document the title block banner is not set to the indicated color. 

```
---
format: html
---

```{r}
#| results: asis
#| eval: true
#| echo: false

ymlthis::yml_empty() |> 
  ymlthis::yml_toplevel(
    title = "Testing Title",
    subtitle = "Testing Subtitle",
    "title-block-banner" = "#527798")
```


```

**Comment by malcolmbarrett** [comment]
Oh yeah, that's not what ymlthis does. 

For Quarto, if you're using it to support correct YAML, I recommend leaning on autocomplete and Quarto's built-in  YAML validation. If you're trying to work with the metadata programmatically, you might want to use a [Lua filter](https://quarto.org/docs/extensions/filters.html) (see [this example](https://stackoverflow.com/questions/77882406/how-to-access-meta-data-from-quarto-yaml-in-lua-script), too)
